# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f599347ac1d7b05247f777bcbc763f39f0ab63b00c12c22ac523891b1daa6193d984ac7a91c37f73639ba8d8f642af67648dee0d63b57902f32c7a01d5f8d604

test:
  secret_key_base: 59fcbefe59ee4707b0885f9b948cc2db01e6543de8d28c17d15400fb4162b7f28441cc292afec5e43c772fca6df9de70791ae2252921c6c3d1c03783196bcae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
